"""SHOWDOWN phase 2 — Reading the Table (docs/phases/showdown/phase-2/).

The showdown rule is hidden behind an opaque `table_rule` codename and changes every
leg. These tests pin the inference: learn the rule from the showdowns in
`recent_hands`, keep what we learn per codename, and never let an unknown table make
us bet as though it were the standard one.
"""
import json

from fastapi.testclient import TestClient

from app.main import app
from app.showdown_rules import (
    KNOWN_RULES,
    RULES,
    RuleBelief,
    forget_all,
    observe,
    posterior_for,
    rule_equity,
    showdown_winners,
)

client = TestClient(app)


def setup_function():
    forget_all()  # each test starts with no memory of any codename


# ───────────────────────────── the rule representation ──────────────────────────


def test_every_rule_is_a_total_ordering_over_the_deck():
    for rule in RULES:
        for c in range(1, 14):
            keys = [rule.key(n, c) for n in range(1, 14)]
            assert len(keys) == 13
            # keys must be mutually comparable, i.e. sortable without error
            sorted(keys)


def test_the_standard_rule_reproduces_the_guides_showdown():
    std = next(r for r in RULES if r.name == "standard")
    # "any pair beats any non-pair", then "the higher number wins", else a split
    assert showdown_winners(std, {0: 7, 1: 13}, community=7) == [0]
    assert showdown_winners(std, {0: 9, 1: 11}, community=3) == [1]
    assert showdown_winners(std, {0: 6, 1: 6}, community=2) == [0, 1]
    assert showdown_winners(std, {0: 5, 1: 5}, community=5) == [0, 1]


def test_the_rule_the_statement_says_is_not_in_play_is_absent():
    # "Odd numbers beat even numbers; within each group, higher still wins." —
    # we are told it is not in play, so it gets no prior mass
    from app.showdown_rules import EXCLUDED, _signature

    excluded = _signature(EXCLUDED)
    assert all(_signature(rule) != excluded for rule in RULES)


def test_no_two_hypotheses_are_the_same_rule_in_disguise():
    # duplicates would split the posterior between identical explanations and
    # halve our confidence for no reason
    from app.showdown_rules import _signature

    seen = {}
    for rule in RULES:
        sig = _signature(rule)
        assert sig not in seen, f"{rule.name} is really {seen.get(sig)}"
        seen[sig] = rule.name


# ──────────────────────────────── learning a rule ───────────────────────────────


def hand(numbers, community, winners, hand_number=1):
    return {
        "hand_number": hand_number,
        "community_number": community,
        "winners": winners,
        "pot": 20,
        "shown_numbers": {str(k): v for k, v in numbers.items()},
        "actions": [],
    }


def teach(codename, rule_name, hands=40, seed=0):
    """Feed the store real showdowns generated by one rule."""
    import random

    rng = random.Random(seed)
    rule = next(r for r in RULES if r.name == rule_name)
    for i in range(hands):
        a, b, c = rng.randint(1, 13), rng.randint(1, 13), rng.randint(1, 13)
        observe(
            codename,
            match_id=f"m{i}",
            leg=1,
            hand_number=i + 1,
            numbers={0: a, 1: b},
            community=c,
            winners=showdown_winners(rule, {0: a, 1: b}, c),
        )
    return rule


def test_an_unseen_codename_starts_at_the_phase_one_rule():
    # deliberately NOT flat. Three of the four real phase-2 tables were best
    # explained by phase 1's rule, so an unknown table starts there and lets
    # evidence move it; a flat prior over thirty hypotheses leaves us at a coin
    # flip for the first dozen hands of a 40-hand leg.
    belief = posterior_for("chalcedony")
    assert abs(sum(belief.values()) - 1.0) < 1e-9
    assert max(belief, key=belief.get) == "standard"
    assert 0.3 < belief["standard"] < 0.6, "a prior, not a conviction"


def test_evidence_still_overrules_the_prior():
    teach("contrary", "low", hands=40, seed=8)
    belief = posterior_for("contrary")
    assert belief["standard"] < 0.01
    assert rule_equity(belief, 1, 5) > 0.8


def test_an_all_in_refund_is_not_treated_as_a_tie():
    # Two winners holding DIFFERENT numbers is not a split — when both players
    # are all in, chips nobody could cover go back and the log lists both seats.
    # Every one we have seen came from a pot of 127-405 against a median of 8
    # for decided hands. Believing them made three tables look like the deck was
    # grouped into bands, and cost us a leg.
    assert not observe("refund", match_id="m", leg=1, hand_number=1,
                       numbers={0: 12, 1: 13}, community=4, winners=[0, 1],
                       pot=405, starting_stack=200)
    assert RuleBelief.for_codename("refund").count == 0
    # a genuine tie — identical numbers — is still evidence at any pot size
    assert observe("refund", match_id="m", leg=1, hand_number=2,
                   numbers={0: 9, 1: 9}, community=4, winners=[0, 1],
                   pot=405, starting_stack=200)
    # and so is an honest tie between DIFFERENT numbers in a normal pot: under
    # "closest to the community" a 3 and a 7 both sit two away from a 5, so the
    # numbers alone must not condemn it — only an all-in-sized pot does
    assert observe("refund", match_id="m", leg=1, hand_number=3,
                   numbers={0: 3, 1: 7}, community=5, winners=[0, 1],
                   pot=8, starting_stack=200)
    assert RuleBelief.for_codename("refund").count == 2


def test_a_lucky_number_rule_is_learnable():
    # amaranth: a 7 beat an 8 twice at different community numbers, and never lost
    teach("lucky", "lucky7", hands=60, seed=2)
    belief = posterior_for("lucky")
    truth = {"lucky7": 1.0}
    worst = max(abs(rule_equity(belief, n, c) - rule_equity(truth, n, c))
                for n in range(1, 14) for c in range(1, 14))
    assert worst < 0.10, belief


def test_the_seed_file_survives_a_restart():
    from app.showdown_rules import load_seed

    forget_all()
    assert load_seed() > 0
    for codename in ("verdigris", "cinnabar", "amaranth", "obsidian"):
        assert RuleBelief.for_codename(codename).count > 0, codename


def test_the_dump_round_trips_through_the_seed_loader():
    import json as _json
    import tempfile

    from app.showdown_rules import load_seed, observations_dump

    teach("roundtrip", "near", hands=12, seed=4)
    dumped = observations_dump()
    assert dumped["tables"]["roundtrip"]
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
        _json.dump(dumped, fh)
        path = fh.name
    forget_all()
    assert load_seed(path) == 12
    assert RuleBelief.for_codename("roundtrip").count == 12


def test_forty_showdowns_teach_us_to_value_hands_correctly():
    # what matters is not naming the rule but pricing hands under it: two rules
    # that differ only on an exact-distance tie-break are the same to us
    for name in ("standard", "low", "near", "wrap_up", "antipair_high", "sum_mod",
                 "far", "even_high", "pair_low", "high"):
        forget_all()
        teach("codename-" + name, name, hands=40, seed=3)
        learned = posterior_for("codename-" + name)
        truth = {name: 1.0}
        worst = max(
            abs(rule_equity(learned, n, c) - rule_equity(truth, n, c))
            for n in range(1, 14)
            for c in range(1, 14)
        )
        # 40 showdowns against ~58 hypotheses cannot fully separate rules that
        # differ only on hands nobody was dealt — teaching "highest wins" leaves a
        # little mass on "a 13 beats everything", which differs only when someone
        # pairs. Hedging between them is correct, so the bar is that we price
        # hands close to the truth, not that we name it outright.
        assert worst < 0.10, f"{name}: equity off by {worst:.3f}; belief={learned}"
        assert learned[name] > 0.30, f"{name}: true rule only got {learned[name]:.3f}"


def test_learning_is_kept_per_codename_and_does_not_bleed():
    teach("aaa", "low", hands=40, seed=1)
    teach("bbb", "near", hands=40, seed=2)
    assert max(posterior_for("aaa"), key=posterior_for("aaa").get) == "low"
    assert max(posterior_for("bbb"), key=posterior_for("bbb").get) == "near"


def test_the_same_hand_seen_twice_is_only_counted_once():
    # recent_hands repeats the same completed hands on every request
    for _ in range(5):
        observe("dup", match_id="m", leg=1, hand_number=1,
                numbers={0: 13, 1: 12}, community=4, winners=[0])
    assert RuleBelief.for_codename("dup").count == 1


def test_standard_is_pinned_so_phase_one_never_regresses():
    # phase 1 announces table_rule "standard" and the guide spells that showdown
    # out in full, so it is known, not inferred
    assert KNOWN_RULES["standard"] == "standard"
    assert posterior_for("standard")["standard"] == 1.0


def test_a_contradictory_observation_does_not_kill_a_rule_outright():
    teach("noisy", "standard", hands=30, seed=5)
    observe("noisy", match_id="x", leg=1, hand_number=99,
            numbers={0: 1, 1: 13}, community=9, winners=[0])  # impossible
    belief = posterior_for("noisy")
    assert max(belief, key=belief.get) == "standard"
    assert belief["standard"] > 0.5


# ─────────────────────────── equity follows the belief ──────────────────────────


def test_equity_under_the_standard_rule_matches_the_closed_form():
    from app.showdown import equity

    std = {"standard": 1.0}
    for n in range(1, 14):
        for c in range(1, 14):
            assert abs(rule_equity(std, n, c) - equity(n, c)) < 1e-9
        assert abs(rule_equity(std, n, None) - equity(n, None)) < 1e-9


def test_equity_inverts_when_the_rule_inverts():
    low = {"low": 1.0}
    # under "lower wins", a 1 is the monster and a 13 is the trash
    assert rule_equity(low, 1, 7) > 0.9
    assert rule_equity(low, 13, 7) < 0.1


def test_an_undecided_belief_pulls_equity_toward_a_coin_flip():
    flat = {r.name: 1 / len(RULES) for r in RULES}
    spread = [rule_equity(flat, n, 7) for n in range(1, 14)]
    assert max(spread) - min(spread) < 0.55, "unknown table must not look confident"


# ─────────────────────────────── the wire protocol ──────────────────────────────


BASE = {
    "protocol_version": 2,
    "match_id": "phase2-leg3",
    "phase": 2,
    "table_rule": "chalcedony",
    "small_blind": 1,
    "big_blind": 2,
    "starting_stack": 200,
    "your_stack": 200,
    "hand_number": 1,
    "total_hands": 40,
    "leg_number": 3,
    "total_legs": 4,
    "round": "post_reveal",
    "your_number": 13,
    "community_number": 5,
    "your_seat": 0,
    "button_seat": 1,
    "pot": 20,
    "to_call": 0,
    "min_raise_to": 2,
    "max_raise_to": 200,
    "legal_actions": ["check", "bet"],
    "players": [
        {"seat": 0, "name": "you", "folded": False, "chip_delta": 0,
         "bet_this_round": 0, "stack": 200, "all_in": False, "busted": False},
        {"seat": 1, "name": "Wren", "folded": False, "chip_delta": 0,
         "bet_this_round": 0, "stack": 200, "all_in": False, "busted": False},
    ],
    "current_hand_actions": [],
    "recent_hands": [],
}


def move(**over):
    body = json.loads(json.dumps(BASE))
    body.update(over)
    return client.post("/move", json=body)


def test_a_leg_request_is_answered_legally():
    r = move()
    assert r.status_code == 200
    assert r.json()["action"] in BASE["legal_actions"]


def test_new_leg_fields_do_not_break_anything():
    for legs in ((None, None), (1, 4), (4, 4)):
        r = move(leg_number=legs[0], total_legs=legs[1])
        assert r.status_code == 200, legs


def test_recent_hands_from_the_wire_teach_the_rule():
    # a "lower wins" table: play the shown hands through /move and the codename
    # should end up believing it
    low = next(r for r in RULES if r.name == "low")
    import random

    rng = random.Random(11)
    hands = []
    for i in range(20):
        a, b, c = rng.randint(1, 13), rng.randint(1, 13), rng.randint(1, 13)
        hands.append(hand({0: a, 1: b}, c, showdown_winners(low, {0: a, 1: b}, c), i + 1))
    move(table_rule="opal", recent_hands=hands, hand_number=21)
    belief = posterior_for("opal")
    assert RuleBelief.for_codename("opal").count == 20
    # 20 hands narrow it to the "lower wins" family but need not separate `low`
    # from `antipair_low`: they differ only when the LOWER number is the one that
    # pairs, which may simply not have come up. What matters is that we now price
    # a 1 as the monster and a 13 as the trash.
    assert rule_equity(belief, 1, 5) > 0.80, belief
    assert rule_equity(belief, 13, 5) < 0.20, belief
    top2 = [n for n, _ in sorted(belief.items(), key=lambda kv: -kv[1])[:2]]
    assert "low" in top2, belief


def test_a_number_that_is_trash_under_the_learned_rule_is_not_bet_big():
    # teach "lower wins", then offer a 13 — phase 1's model would call it 89%
    teach("jade", "low", hands=40, seed=7)
    body = move(table_rule="jade", your_number=13, community_number=5).json()
    assert body["action"] == "check", body


def test_the_same_number_is_a_monster_under_the_mirrored_rule():
    teach("jade", "low", hands=40, seed=7)
    body = move(table_rule="jade", your_number=1, community_number=5).json()
    assert body["action"] == "bet", body


def test_hands_that_ended_before_showdown_are_not_used_as_evidence():
    # "a hand won by a fold shows nothing, and that hand's community_number is
    # null too if it ended before the reveal"
    folded = [
        {"hand_number": 1, "community_number": None, "winners": [1], "pot": 6,
         "shown_numbers": {}, "actions": []},
        {"hand_number": 2, "community_number": 9, "winners": [0], "pot": 8,
         "shown_numbers": {"0": 4}, "actions": []},
    ]
    move(table_rule="quartz", recent_hands=folded, hand_number=3)
    assert RuleBelief.for_codename("quartz").count == 0


def test_garbage_recent_hands_never_break_the_endpoint():
    for junk in ([{"shown_numbers": "nope"}], [None], ["x"], [{"winners": "0"}],
                 [{"shown_numbers": {"0": 99, "1": -3}, "community_number": 5, "winners": [0]}]):
        r = move(table_rule="junk", recent_hands=junk)
        assert r.status_code == 200, junk
        assert r.json()["action"] in BASE["legal_actions"]


def test_phase_one_behaviour_is_unchanged_under_the_standard_codename():
    # the guide's worked example, still a fold
    r = move(
        table_rule="standard", leg_number=None, total_legs=None, phase=1,
        total_hands=100, hand_number=6, your_number=3, community_number=5,
        your_stack=185, pot=32, to_call=18, min_raise_to=36, max_raise_to=185,
        legal_actions=["fold", "call", "raise"],
    )
    assert r.json() == {"action": "fold"}


def test_a_long_lived_process_still_answers_fast():
    # the belief is recomputed whenever a new showdown arrives, and a codename
    # accumulates observations across every leg and retry — so the cost has to
    # stay flat against a store far larger than one attempt produces
    import time

    from app.showdown_rules import showdown_winners
    from app.showdown_rules import BY_NAME as _BY

    rng = __import__("random").Random(2)
    rule = _BY["near"]
    for i in range(600):
        a, b, c = rng.randint(1, 13), rng.randint(1, 13), rng.randint(1, 13)
        observe("busy", match_id=f"m{i // 40}", leg=1, hand_number=i,
                numbers={0: a, 1: b}, community=c,
                winners=showdown_winners(rule, {0: a, 1: b}, c))
    assert RuleBelief.for_codename("busy").count == 600

    start = time.perf_counter()
    for i in range(20):
        hands = [hand({0: rng.randint(1, 13), 1: rng.randint(1, 13)},
                      rng.randint(1, 13), [0], 5000 + i * 20 + j) for j in range(20)]
        r = move(table_rule="busy", recent_hands=hands)
        assert r.status_code == 200
    per_call = (time.perf_counter() - start) / 20
    assert per_call < 0.25, f"{per_call * 1000:.0f} ms per /move against a 5 s budget"
